name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.x
      
    - name: Install dependencies
      run: npm install --production
      
    - name: Build
      run: npm run build
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_URL}}
        FTP_USERNAME: ${{secrets.FTP_USER}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        METHOD: sftp
        LOCAL_DIR: public
